/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.border.EtchedBorder;

/**
 *
 * @author Thales Muller
 */
public class JFrame_calculadora extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_calculadora
     */
    //variables 
    double valor1, valor2, resultado;
    char op = ' ';

    public JFrame_calculadora() {
        initComponents();
        jLabel_Tela.setBorder(new EtchedBorder());
        jLabel_Tela.setText("0");
        valor1 = 0;
        valor2 = 0;
        resultado = 0;
        jPanel_principal.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_principal = new javax.swing.JPanel();
        jLabel_Tela = new javax.swing.JLabel();
        jButton_n7 = new javax.swing.JButton();
        jButton_n4 = new javax.swing.JButton();
        jButton_n1 = new javax.swing.JButton();
        jButton_n0 = new javax.swing.JButton();
        jButton_n2 = new javax.swing.JButton();
        jButton_n5 = new javax.swing.JButton();
        jButton_n8 = new javax.swing.JButton();
        jButton_n9 = new javax.swing.JButton();
        jButton_n6 = new javax.swing.JButton();
        jButton_n3 = new javax.swing.JButton();
        jButton_divisao = new javax.swing.JButton();
        jButton_multiplicar = new javax.swing.JButton();
        jButton_menos = new javax.swing.JButton();
        jButton_soma = new javax.swing.JButton();
        jButton_Clear = new javax.swing.JButton();
        jButton_ponto = new javax.swing.JButton();
        jButton_resultado = new javax.swing.JButton();
        jButton_raiz = new javax.swing.JButton();
        jButton_backspace = new javax.swing.JButton();
        jLabel_visor_temporario = new javax.swing.JLabel();
        jButton_trocarsinal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setResizable(false);

        jPanel_principal.setToolTipText("");

        jLabel_Tela.setFont(new java.awt.Font("Cambria", 0, 48)); // NOI18N
        jLabel_Tela.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Tela.setText("0");

        jButton_n7.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jButton_n7.setText("7");
        jButton_n7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_n7ActionPerformed(evt);
            }
        });

        jButton_n4.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jButton_n4.setText("4");
        jButton_n4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_n4ActionPerformed(evt);
            }
        });

        jButton_n1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jButton_n1.setText("1");
        jButton_n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_n1ActionPerformed(evt);
            }
        });

        jButton_n0.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jButton_n0.setText("0");
        jButton_n0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_n0ActionPerformed(evt);
            }
        });

        jButton_n2.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jButton_n2.setText("2");
        jButton_n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_n2ActionPerformed(evt);
            }
        });

        jButton_n5.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jButton_n5.setText("5");
        jButton_n5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_n5ActionPerformed(evt);
            }
        });

        jButton_n8.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jButton_n8.setText("8");
        jButton_n8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_n8ActionPerformed(evt);
            }
        });

        jButton_n9.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jButton_n9.setText("9");
        jButton_n9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_n9ActionPerformed(evt);
            }
        });

        jButton_n6.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jButton_n6.setText("6");
        jButton_n6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_n6ActionPerformed(evt);
            }
        });

        jButton_n3.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jButton_n3.setText("3");
        jButton_n3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_n3ActionPerformed(evt);
            }
        });

        jButton_divisao.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jButton_divisao.setText("/");
        jButton_divisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_divisaoActionPerformed(evt);
            }
        });

        jButton_multiplicar.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jButton_multiplicar.setText("x");
        jButton_multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_multiplicarActionPerformed(evt);
            }
        });

        jButton_menos.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jButton_menos.setText("-");
        jButton_menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_menosActionPerformed(evt);
            }
        });

        jButton_soma.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jButton_soma.setText("+");
        jButton_soma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_somaActionPerformed(evt);
            }
        });

        jButton_Clear.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jButton_Clear.setText("C");
        jButton_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClearActionPerformed(evt);
            }
        });

        jButton_ponto.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jButton_ponto.setText(".");
        jButton_ponto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_pontoActionPerformed(evt);
            }
        });

        jButton_resultado.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jButton_resultado.setText("=");
        jButton_resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_resultadoActionPerformed(evt);
            }
        });

        jButton_raiz.setText("√");
        jButton_raiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_raizActionPerformed(evt);
            }
        });

        jButton_backspace.setText("<-");
        jButton_backspace.setToolTipText("");
        jButton_backspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_backspaceActionPerformed(evt);
            }
        });

        jLabel_visor_temporario.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel_visor_temporario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jButton_trocarsinal.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jButton_trocarsinal.setText("+-");
        jButton_trocarsinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_trocarsinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_principalLayout = new javax.swing.GroupLayout(jPanel_principal);
        jPanel_principal.setLayout(jPanel_principalLayout);
        jPanel_principalLayout.setHorizontalGroup(
            jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_principalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel_principalLayout.createSequentialGroup()
                        .addComponent(jButton_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_backspace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_raiz)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_divisao, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_principalLayout.createSequentialGroup()
                        .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_n4)
                            .addComponent(jButton_n1)
                            .addComponent(jButton_n7)
                            .addComponent(jButton_trocarsinal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_principalLayout.createSequentialGroup()
                                .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton_n5)
                                        .addComponent(jButton_n0))
                                    .addComponent(jButton_n2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_ponto)
                                    .addComponent(jButton_n3)
                                    .addComponent(jButton_n6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_menos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_soma)
                                    .addComponent(jButton_resultado)))
                            .addGroup(jPanel_principalLayout.createSequentialGroup()
                                .addComponent(jButton_n8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_n9)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel_Tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_principalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_visor_temporario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel_principalLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton_Clear, jButton_backspace, jButton_divisao, jButton_menos, jButton_multiplicar, jButton_n0, jButton_n1, jButton_n2, jButton_n3, jButton_n4, jButton_n5, jButton_n6, jButton_n7, jButton_n8, jButton_n9, jButton_ponto, jButton_raiz, jButton_resultado, jButton_soma});

        jPanel_principalLayout.setVerticalGroup(
            jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_visor_temporario, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Tela, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_divisao)
                    .addComponent(jButton_raiz)
                    .addComponent(jButton_backspace, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Clear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_principalLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_n0)
                            .addComponent(jButton_ponto)
                            .addComponent(jButton_resultado)
                            .addComponent(jButton_trocarsinal))
                        .addContainerGap())
                    .addGroup(jPanel_principalLayout.createSequentialGroup()
                        .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_n7)
                            .addComponent(jButton_n8)
                            .addComponent(jButton_n9)
                            .addComponent(jButton_multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_n4)
                            .addComponent(jButton_n5)
                            .addComponent(jButton_n6)
                            .addComponent(jButton_menos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_n1)
                            .addComponent(jButton_n2)
                            .addComponent(jButton_n3)
                            .addComponent(jButton_soma))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel_principalLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton_Clear, jButton_backspace, jButton_divisao, jButton_menos, jButton_multiplicar, jButton_n0, jButton_n1, jButton_n2, jButton_n3, jButton_n4, jButton_n5, jButton_n6, jButton_n7, jButton_n8, jButton_n9, jButton_ponto, jButton_raiz, jButton_resultado, jButton_soma});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jButton_n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_n1ActionPerformed
        // TODO add your handling code here:
        SetarNumerodoLabel('1');

    }//GEN-LAST:event_jButton_n1ActionPerformed

    private void jButton_n5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_n5ActionPerformed
        // TODO add your handling code here:
        SetarNumerodoLabel('5');
    }//GEN-LAST:event_jButton_n5ActionPerformed

    private void jButton_n2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_n2ActionPerformed
        // TODO add your handling code here:
        SetarNumerodoLabel('2');
    }//GEN-LAST:event_jButton_n2ActionPerformed

    private void jButton_n3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_n3ActionPerformed
        // TODO add your handling code here:
        SetarNumerodoLabel('3');
    }//GEN-LAST:event_jButton_n3ActionPerformed

    private void jButton_n4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_n4ActionPerformed
        // TODO add your handling code here:
        SetarNumerodoLabel('4');
    }//GEN-LAST:event_jButton_n4ActionPerformed

    private void jButton_n6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_n6ActionPerformed
        // TODO add your handling code here:
        SetarNumerodoLabel('6');
    }//GEN-LAST:event_jButton_n6ActionPerformed

    private void jButton_n7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_n7ActionPerformed
        // TODO add your handling code here:
        SetarNumerodoLabel('7');
    }//GEN-LAST:event_jButton_n7ActionPerformed

    private void jButton_n8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_n8ActionPerformed
        // TODO add your handling code here:
        SetarNumerodoLabel('8');
    }//GEN-LAST:event_jButton_n8ActionPerformed

    private void jButton_n9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_n9ActionPerformed
        // TODO add your handling code here:
        SetarNumerodoLabel('9');
    }//GEN-LAST:event_jButton_n9ActionPerformed

    private void jButton_n0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_n0ActionPerformed
        // TODO add your handling code here:
        SetarNumerodoLabel('0');
    }//GEN-LAST:event_jButton_n0ActionPerformed

    private void jButton_pontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_pontoActionPerformed
        // TODO add your handling code here:
        /*
        t= jLabel_Tela.getText();
        i = t.length();
                
        if( jLabel_Tela.getText() == ""){
            jLabel_Tela.setText("0.");
        }
        else if(jLabel_Tela.getText() == "0."){
            jLabel_Tela.setText("0.");
        }
        /*
        else if(i>0){
            System.out.println("t"+t);
            char[] c = t.toString().toCharArray();
            System.out.println("c:"+c[i-1] +" -- i:" +i);
            if (c[i-1] != '.'){
                //SetarNumerodoLabel('.');
            }
            System.out.println(c[i-1]);
        }
        
        else{
         */
        SetarNumerodoLabel('.');
        //}
    }//GEN-LAST:event_jButton_pontoActionPerformed

    private void jButton_raizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_raizActionPerformed
        // TODO add your handling code here:
        SetValor1();
        op = '√';
        Calcular();
        SetVisorTemp();
    }//GEN-LAST:event_jButton_raizActionPerformed

    private void jButton_somaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_somaActionPerformed
        // TODO add your handling code here:
        SetValor1();
        op = '+';
        SetVisorTemp();
    }//GEN-LAST:event_jButton_somaActionPerformed

    private void jButton_divisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_divisaoActionPerformed
        // TODO add your handling code here:
        SetValor1();
        op = '/';
        SetVisorTemp();
    }//GEN-LAST:event_jButton_divisaoActionPerformed

    private void jButton_multiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_multiplicarActionPerformed
        // TODO add your handling code here:
        SetValor1();
        op = '*';
        SetVisorTemp();
    }//GEN-LAST:event_jButton_multiplicarActionPerformed

    private void jButton_menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_menosActionPerformed
        // TODO add your handling code here:
        SetValor1();
        op = '-';
        SetVisorTemp();
    }//GEN-LAST:event_jButton_menosActionPerformed

    private void jButton_resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_resultadoActionPerformed
        // TODO add your handling code here:
        SetValor2();
        Calcular();
        SetVisorTempTotal();
    }//GEN-LAST:event_jButton_resultadoActionPerformed

    private void jButton_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearActionPerformed
        // TODO add your handling code here:
        Clear();
    }//GEN-LAST:event_jButton_ClearActionPerformed

    private void jButton_backspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_backspaceActionPerformed
        // TODO add your handling code here:
        Backspace();

    }//GEN-LAST:event_jButton_backspaceActionPerformed

    private void jButton_trocarsinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_trocarsinalActionPerformed
        // TODO add your handling code here:
        TrocarSinal();
    }//GEN-LAST:event_jButton_trocarsinalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_calculadora().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Clear;
    private javax.swing.JButton jButton_backspace;
    private javax.swing.JButton jButton_divisao;
    private javax.swing.JButton jButton_menos;
    private javax.swing.JButton jButton_multiplicar;
    private javax.swing.JButton jButton_n0;
    private javax.swing.JButton jButton_n1;
    private javax.swing.JButton jButton_n2;
    private javax.swing.JButton jButton_n3;
    private javax.swing.JButton jButton_n4;
    private javax.swing.JButton jButton_n5;
    private javax.swing.JButton jButton_n6;
    private javax.swing.JButton jButton_n7;
    private javax.swing.JButton jButton_n8;
    private javax.swing.JButton jButton_n9;
    private javax.swing.JButton jButton_ponto;
    private javax.swing.JButton jButton_raiz;
    private javax.swing.JButton jButton_resultado;
    private javax.swing.JButton jButton_soma;
    private javax.swing.JButton jButton_trocarsinal;
    private javax.swing.JLabel jLabel_Tela;
    private javax.swing.JLabel jLabel_visor_temporario;
    private javax.swing.JPanel jPanel_principal;
    // End of variables declaration//GEN-END:variables

    //Metodos
    public void SetarNumerodoLabel(char numero) {

        if ("0".equals(jLabel_Tela.getText()) && !".".equals(String.valueOf(numero))) { // para nao ficar 0 antes de operações
            jLabel_Tela.setText("");
        }

        if (jLabel_Tela.getText().length() <= 7) {
            String texto = jLabel_Tela.getText();
            texto = texto + numero;
            jLabel_Tela.setText(texto);
        }
        jPanel_principal.requestFocus(); // voltar a focar no painel e permitir digitar novamente

    }

    public void SetValor1() {

        valor1 = Double.parseDouble(jLabel_Tela.getText());
        jLabel_Tela.setText("0");
        jPanel_principal.requestFocus();
    }

    public void SetValor2() {
        valor2 = Double.parseDouble(jLabel_Tela.getText());
        jLabel_Tela.setText("");
        jPanel_principal.requestFocus();
    }

    public void Calcular() {

        if (valor2 != 0 || op != '/') {
            switch (op) {

                case '+':
                    resultado = valor1 + valor2;
                    break;
                case '-':
                    resultado = valor1 - valor2;
                    break;
                case '*':
                    resultado = valor1 * valor2;
                    break;
                case '/':
                    resultado = valor1 / valor2;
                    break;
                case '√':
                    resultado = Math.sqrt(valor1);
                    break;
                default:
                    break;
            }
            //System.out.println(resultado); ///TESTE

            jLabel_Tela.setText(String.valueOf(resultado));
        } else {
            jLabel_Tela.setText("ERROR!");
        }

        jPanel_principal.requestFocus();
    }

    public void Clear() {
        ReiniciarCalculadora();
        jPanel_principal.requestFocus();
    }

    public void ReiniciarCalculadora() {
        valor1 = 0;
        valor2 = 0;
        resultado = 0;
        op = ' ';
        jLabel_Tela.setText("0");
        jLabel_visor_temporario.setText(" ");
    }

    public void Backspace() {
        if (jLabel_Tela.getText().length() > 0) {
            String valor_JLabelTela = jLabel_Tela.getText();
            valor_JLabelTela = valor_JLabelTela.substring(0, valor_JLabelTela.length() - 1);
            jLabel_Tela.setText(valor_JLabelTela);

            if (jLabel_Tela.getText().length() == 0) {
                jLabel_Tela.setText("0");
            }
        } else {
            jLabel_Tela.setText("0");
        }
        jPanel_principal.requestFocus();
    }

    public void SetVisorTemp() {
        jLabel_visor_temporario.setText(valor1 + "  " + op);
    }

    public void SetVisorTempTotal() {
        jLabel_visor_temporario.setText(valor1 + "  " + op + "  " + valor2);
    }

    public void TrocarSinal() {
        double inversao = Double.parseDouble(jLabel_Tela.getText());
        if (inversao != 0) {

            inversao = inversao * -1;
            jLabel_Tela.setText(String.valueOf(inversao));
        }
        jPanel_principal.requestFocus();
    }

}
